### PR TITLE
Dockerizing bellman repo

### PR DESCRIPTION
**Pull request by fleupold**
Inline with the other folders in this repo.

### CODE REVIEW

**Review by Uxio0 — APPROVED** [review]
Seems good to me, good work @fleupold

**Comment by fleupold** [comment]
The build is failing because "gnosispm/dex_bellman:staging" doesn't exist yet. @Uxio0, should I first create it without a cached build and then make the build cached in a separate PR or is there an easier way to do it?

**Comment by Uxio0** [comment]
Hi @fleupold, that's right. I think the easier would be to create the repo beforehand, but you can take a look on this script we use for the Safe Relay: https://github.com/gnosis/safe-relay-service/blob/master/scripts/deploy_docker.sh

**Review by bh2smith — COMMENTED** [review]
Seems legit. Any reason you are always making the docker user? Why not just log in as root? Are we trying to protect the OS files?

**Pull request merged**
