### PR TITLE
adding a script that can convert libsnark binary output to non binary

### PR DESCRIPTION
**Pull request by fleupold**
If you forget to compile pepper with `-UBINARY_OUTPUT` any output (e.g. the exported witness) will be in binary and not human readable.

This script allows to read such an output file and convert its content into a non binary output format.

### CODE REVIEW

**Comment by bh2smith** [comment]
This looks really great although I am not sure how to use it. I found that `make scripts` tells me its already made, but then I wouldn't know how to call the function. Do I need to supply a binary file? Are these the files that I find in prover_verifier_shared?

**Comment by fleupold** [comment]
The binary file will be put into `scripts/bin/pepper_binary_format_reader` (cf. make command). The input would be a witness file you receive from generating a witness inside the pepper framework (e.g. `./bin/pepper_prover_hash_transform witness hash_transform.inputs hash_transform.witness`)

This is assuming pepper was compiled with `-DBINARY_OUTPUT` (the default, which makes your witness be exported in binary instead of ASCII). If you remembered change the pepper Makefile to use `-UBINARY_OUTPUT`, you won't need this script.

**Review by bh2smith — APPROVED** [review]
I have seen this working on a binary output for hash transform witness and it seems to add up! Cool stuff. Seems very useful!

**Comment by fleupold** [comment]
Thanks for testing it on your machine @bh2smith

**Pull request merged**
